export interface Tournament {
  name: string;
  tour: string;
  innerColor: string;
  outerColor: string;
  startDate: string; // YYYY‑MM‑DD
  endDate: string;   // YYYY‑MM‑DD
  location?: string; // Optional location for the tournament
  city?: string;    // Optional city for the tournament
  surface?: string; // Optional surface type (e.g., "Hard", "Clay", "Grass")
  link?: string; // Optional link to the tournament website or details
  surfaceText?: string; // Optional text for additional information
}

export type TourType = 'ATP' | 'WTA';

export type CourtSurface = 'Hard' | 'Clay' | 'Grass' | 'Carpet' | 'Other';

export interface TournamentNext {
  name: string;
  tour: TourType[]; // Array of supported tours
  points: number; // Ranking points awarded

  startDate: string; // Format: YYYY-MM-DD
  endDate: string;

  court: {
    innerColor: string; // Used for UI surface color
    outerColor: string; // Used for UI border color
    surface: CourtSurface; // Add an explicit surface type for filtering/styling
    surfaceText?: string; // Optional description (e.g., "Indoor Hard", "Green Clay")
  };

  location: {
    city: string;
    country: string;
  };

  links: {
    atp?: string; // Official ATP page
    wta?: string; // Official WTA page
    officialSite?: string; // Optional — event website
  };
}

export const tournamentsNext: TournamentNext[] = [

]

export const t: Tournament[] =
  [
    {
      name: 'United Cup',
      tour: 'United Cup',
      location: 'United Cup',
      city: 'Perth‑Sydney',
      link: '/en/tournaments/perth-sydney/9900/overview',
      surface: 'Hard',
      innerColor: '#0297DB',
      outerColor: '#E8F7FF',
      startDate: '2024-12-27',
      endDate: '2025-01-05',
    },
    {
      name: 'Brisbane, Australia',
      tour: 'ATP 250',
      location: 'Brisbane International presented by Evie',
      city: 'Brisbane',
      link: '/en/tournaments/brisbane/339/overview',
      surface: 'Hard',
      innerColor: '#0297DB',
      outerColor: '#E8F7FF',
      startDate: '2024-12-29',
      endDate: '2025-01-05',
    },
    {
      name: 'Hong Kong, Hong Kong',
      tour: 'ATP 250',
      location: 'Bank of China Hong Kong Tennis Open',
      city: 'Hong Kong',
      link: '/en/tournaments/hong-kong/336/overview',
      surface: 'Hard',
      innerColor: '#0297DB',
      outerColor: '#E8F7FF',
      startDate: '2024-12-30',
      endDate: '2025-01-05',
    },
    {
      name: 'Adelaide, Australia',
      tour: 'ATP 250',
      location: 'Adelaide International',
      city: 'Adelaide',
      link: '/en/tournaments/adelaide/8998/overview',
      surface: 'Hard',
      innerColor: '#0297DB',
      outerColor: '#E8F7FF',
      startDate: '2025-01-06',
      endDate: '2025-01-11',
    },
    {
      name: 'Auckland, New Zealand',
      tour: 'ATP 250',
      location: 'ASB Classic',
      city: 'Auckland',
      link: '/en/tournaments/auckland/301/overview',
      surface: 'Hard',
      innerColor: '#0297DB',
      outerColor: '#E8F7FF',
      startDate: '2025-01-06',
      endDate: '2025-01-11',
    },
    {
      name: 'Australian Open',
      tour: 'Grand Slam',
      location: 'Australian Open',
      city: 'Melbourne',
      link: '/en/tournaments/australian-open/580/overview',
      surface: 'Hard',
      innerColor: '#0297DB',
      outerColor: '#E8F7FF',
      startDate: '2025-01-12',
      endDate: '2025-01-26',
    },
    {
      name: 'Montpellier, France',
      tour: 'ATP 250',
      location: 'Open Occitanie',
      city: 'Montpellier',
      link: '/en/tournaments/montpellier/375/overview',
      surface: 'Hard (Indoor)',
      innerColor: '#1A237E',
      outerColor: '#C5CAE9',
      startDate: '2025-01-27',
      endDate: '2025-02-02',
    },
    {
      name: 'Davis Cup Qualifiers 1st Rd',
      tour: 'ITF',
      location: 'Davis Cup Qualifiers 1st Rd',
      city: 'Multiple Locations',
      link: '/en/tournaments/davis-cup-qualifiers-1st-rd/8096/overview',
      surface: 'N/A',
      innerColor: '#B71C1C',
      outerColor: '#FFCdd2',
      startDate: '2025-01-31',
      endDate: '2025-02-02',
    },
    {
      name: 'Dallas, United States',
      tour: 'ATP 500',
      location: 'Dallas Open',
      city: 'Dallas',
      link: '/en/tournaments/dallas/424/overview',
      surface: 'Hard (Indoor)',
      innerColor: '#1A237E',
      outerColor: '#C5CAE9',
      startDate: '2025-02-03',
      endDate: '2025-02-09',
    },
    {
      name: 'Rotterdam, Netherlands',
      tour: 'ATP 500',
      location: 'ABN AMRO Open',
      city: 'Rotterdam',
      link: '/en/tournaments/rotterdam/407/overview',
      surface: 'Hard (Indoor)',
      innerColor: '#1A237E',
      outerColor: '#C5CAE9',
      startDate: '2025-02-03',
      endDate: '2025-02-09',
    },
    {
      name: 'Marseille, France',
      tour: 'ATP 250',
      location: 'Open 13 Provence',
      city: 'Marseille',
      link: '/en/tournaments/marseille/496/overview',
      surface: 'Hard (Indoor)',
      innerColor: '#1A237E',
      outerColor: '#C5CAE9',
      startDate: '2025-02-10',
      endDate: '2025-02-16',
    },
    {
      name: 'Delray Beach, United States',
      tour: 'ATP 250',
      location: 'Delray Beach Open',
      city: 'Delray Beach',
      link: '/en/tournaments/delray-beach/499/overview',
      surface: 'Hard',
      innerColor: '#0297DB',
      outerColor: '#E8F7FF',
      startDate: '2025-02-10',
      endDate: '2025-02-16',
    },
    {
      name: 'Buenos Aires, Argentina',
      tour: 'ATP 250',
      location: 'IEB+ Argentina Open',
      city: 'Buenos Aires',
      link: '/en/tournaments/buenos-aires/506/overview',
      surface: 'Clay',
      innerColor: '#C23B22',
      outerColor: '#F1F3F4',
      startDate: '2025-02-10',
      endDate: '2025-02-16',
    },
    {
      name: 'Doha, Qatar',
      tour: 'ATP 500',
      location: 'Qatar ExxonMobil Open',
      city: 'Doha',
      link: '/en/tournaments/doha/451/overview',
      surface: 'Hard',
      innerColor: '#0297DB',
      outerColor: '#E8F7FF',
      startDate: '2025-02-17',
      endDate: '2025-02-22',
    },
    {
      name: 'Rio de Janeiro, Brazil',
      tour: 'ATP 500',
      location: 'Rio Open presented by Claro',
      city: 'Rio de Janeiro',
      link: '/en/tournaments/rio-de-janeiro/6932/overview',
      surface: 'Clay',
      innerColor: '#C23B22',
      outerColor: '#F1F3F4',
      startDate: '2025-02-17',
      endDate: '2025-02-23',
    },
    {
      name: 'Dubai, United Arab Emirates',
      tour: 'ATP 500',
      location: 'Dubai Duty Free Tennis Championships',
      city: 'Dubai',
      link: '/en/tournaments/dubai/495/overview',
      surface: 'Hard',
      innerColor: '#5668A7',
      outerColor: '#87A182',
      startDate: '2025-02-24',
      endDate: '2025-03-01',
      surfaceText: 'Dubai',
    },
    {
      'name': 'Acapulco, Mexico',
      'tour': 'ATP 500',
      'location': 'Abierto Mexicano Telcel presentado por HSBC',
      'city': 'Acapulco',
      'link': '/en/tournaments/acapulco/807/overview',
      'surface': 'Hard',
      'innerColor': '#2e7d32',
      'outerColor': '#c8e6c9',
      'startDate': '2025-02-24',
      'endDate': '2025-03-01',
    },
    {
      'name': 'Santiago, Chile',
      'tour': 'ATP 250',
      'location': 'Movistar Chile Open',
      'city': 'Santiago',
      'link': '/en/tournaments/santiago/8996/overview',
      'surface': 'Clay',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-02-24',
      'endDate': '2025-03-02',
    },
    {
      'name': 'Indian Wells, United States',
      'tour': 'ATP 1000',
      'location': 'BNP Paribas Open',
      'city': 'Indian Wells',
      'link': '/en/tournaments/indian-wells/404/overview',
      'surface': 'Hard',
      'innerColor': '#1565c0',
      'outerColor': '#bbdefb',
      'startDate': '2025-03-05',
      'endDate': '2025-03-16',
    },
    {
      'name': 'Miami, United States',
      'tour': 'ATP 1000',
      'location': 'Miami Open presented by Itau',
      'city': 'Miami',
      'link': '/en/tournaments/miami/403/overview',
      'surface': 'Hard',
      'innerColor': '#1565c0',
      'outerColor': '#bbdefb',
      'startDate': '2025-03-19',
      'endDate': '2025-03-30',
    },
    {
      'name': 'Houston, United States',
      'tour': 'ATP 250',
      'location': 'Fayez Sarofim & Co. U.S. Men\'s Clay Court Championship',
      'city': 'Houston',
      'link': '/en/tournaments/houston/717/overview',
      'surface': 'Clay',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-03-31',
      'endDate': '2025-04-06',
    },
    {
      'name': 'Marrakech, Morocco',
      'tour': 'ATP 250',
      'location': 'Grand Prix Hassan II',
      'city': 'Marrakech',
      'link': '/en/tournaments/marrakech/360/overview',
      'surface': 'Clay',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-03-31',
      'endDate': '2025-04-06',
    },
    {
      'name': 'Bucharest, Romania',
      'tour': 'ATP 250',
      'location': 'Tiriac Open presented by UniCredit Bank',
      'city': 'Bucharest',
      'link': '/en/tournaments/bucharest/4462/overview',
      'surface': 'Clay',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-03-31',
      'endDate': '2025-04-06',
    },
    {
      'name': 'Monte-Carlo, Monaco',
      'tour': 'ATP 1000',
      'location': 'Rolex Monte-Carlo Masters',
      'city': 'Monte-Carlo',
      'link': '/en/tournaments/monte-carlo/410/overview',
      'surface': 'Clay',
      'innerColor': '#1565c0',
      'outerColor': '#bbdefb',
      'startDate': '2025-04-06',
      'endDate': '2025-04-13',
    },
    {
      'name': 'Barcelona, Spain',
      'tour': 'ATP 500',
      'location': 'Barcelona Open Banc Sabadell',
      'city': 'Barcelona',
      'link': '/en/tournaments/barcelona/425/overview',
      'surface': 'Clay',
      'innerColor': '#2e7d32',
      'outerColor': '#c8e6c9',
      'startDate': '2025-04-14',
      'endDate': '2025-04-20',
    },
    {
      'name': 'Munich, Germany',
      'tour': 'ATP 500',
      'location': 'BMW Open by Bitpanda',
      'city': 'Munich',
      'link': '/en/tournaments/munich/308/overview',
      'surface': 'Clay',
      'innerColor': '#2e7d32',
      'outerColor': '#c8e6c9',
      'startDate': '2025-04-14',
      'endDate': '2025-04-20',
    },
    {
      'name': 'Madrid, Spain',
      'tour': 'ATP 1000',
      'location': 'Mutua Madrid Open',
      'city': 'Madrid',
      'link': '/en/tournaments/madrid/1536/overview',
      'surface': 'Clay',
      'innerColor': '#1565c0',
      'outerColor': '#bbdefb',
      'startDate': '2025-04-23',
      'endDate': '2025-05-04',
    },
    {
      'name': 'Rome, Italy',
      'tour': 'ATP 1000',
      'location': 'Internazionali BNL d\'Italia',
      'city': 'Rome',
      'link': '/en/tournaments/rome/416/overview',
      'surface': 'Clay',
      'innerColor': '#1565c0',
      'outerColor': '#bbdefb',
      'startDate': '2025-05-07',
      'endDate': '2025-05-18',
    },
    {
      'name': 'Hamburg, Germany',
      'tour': 'ATP 500',
      'location': 'Bitpanda Hamburg Open',
      'city': 'Hamburg',
      'link': '/en/tournaments/hamburg/414/overview',
      'surface': 'Clay',
      'innerColor': '#2e7d32',
      'outerColor': '#c8e6c9',
      'startDate': '2025-05-18',
      'endDate': '2025-05-24',
    },
    {
      'name': 'Geneva, Switzerland',
      'tour': 'ATP 250',
      'location': 'Gonet Geneva Open',
      'city': 'Geneva',
      'link': '/en/tournaments/geneva/322/overview',
      'surface': 'Clay',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-05-18',
      'endDate': '2025-05-24',
    },
    {
      'name': 'Roland Garros',
      'tour': 'Grand Slam',
      'location': 'Roland Garros',
      'city': 'Paris',
      'link': '/en/tournaments/roland-garros/520/overview',
      'surface': 'Clay',
      'innerColor': '#3c1053',
      'outerColor': '#c8a2c8',
      'startDate': '2025-05-25',
      'endDate': '2025-06-08',
    },
    {
      'name': 'Stuttgart, Germany',
      'tour': 'ATP 250',
      'location': 'BOSS OPEN',
      'city': 'Stuttgart',
      'link': '/en/tournaments/stuttgart/321/overview',
      'surface': 'Grass',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-06-09',
      'endDate': '2025-06-15',
    },
    {
      'name': '\'s-Hertogenbosch, Netherlands',
      'tour': 'ATP 250',
      'location': 'Libema Open',
      'city': '\'s-Hertogenbosch',
      'link': '/en/tournaments/s-hertogenbosch/440/overview',
      'surface': 'Grass',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-06-09',
      'endDate': '2025-06-15',
    },
    {
      'name': 'London, Great Britain',
      'tour': 'ATP 500',
      'location': 'HSBC Championships',
      'city': 'London',
      'link': '/en/tournaments/london/311/overview',
      'surface': 'Grass',
      'innerColor': '#2e7d32',
      'outerColor': '#c8e6c9',
      'startDate': '2025-06-16',
      'endDate': '2025-06-22',
    },
    {
      'name': 'Halle, Germany',
      'tour': 'ATP 500',
      'location': 'Terra Wortmann Open',
      'city': 'Halle',
      'link': '/en/tournaments/halle/500/overview',
      'surface': 'Grass',
      'innerColor': '#2e7d32',
      'outerColor': '#c8e6c9',
      'startDate': '2025-06-16',
      'endDate': '2025-06-22',
    },
    {
      'name': 'Mallorca, Spain',
      'tour': 'ATP 250',
      'location': 'Mallorca Championships presented by ecotrans Group',
      'city': 'Mallorca',
      'link': '/en/tournaments/mallorca/8994/overview',
      'surface': 'Grass',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-06-22',
      'endDate': '2025-06-28',
    },
    {
      'name': 'Eastbourne, Great Britain',
      'tour': 'ATP 250',
      'location': 'Lexus Eastbourne Open',
      'city': 'Eastbourne',
      'link': '/en/tournaments/eastbourne/741/overview',
      'surface': 'Grass',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-06-23',
      'endDate': '2025-06-28',
    },
    {
      'name': 'Wimbledon',
      'tour': 'Grand Slam',
      'location': 'Wimbledon',
      'city': 'London',
      'link': '/en/tournaments/wimbledon/540/overview',
      'surface': 'Grass',
      'innerColor': '#868C34',
      'outerColor': '#868C34',
      'startDate': '2025-06-30',
      'endDate': '2025-07-13',
    },
    {
      'name': 'Los Cabos, Mexico',
      'tour': 'ATP 250',
      'location': 'Mifel Tennis Open by Telcel Oppo',
      'city': 'Los Cabos',
      'link': '/en/tournaments/los-cabos/7480/overview',
      'surface': 'Hard',
      'innerColor': '#576491',
      'outerColor': '#928687',
      'startDate': '2025-07-14',
      'endDate': '2025-07-19',
      surfaceText: 'Los Cabos',
    },
    {
      'name': 'Gstaad, Switzerland',
      'tour': 'ATP 250',
      'location': 'EFG Swiss Open Gstaad',
      'city': 'Gstaad',
      'link': '/en/tournaments/gstaad/314/overview',
      'surface': 'Clay',
      'innerColor': '#CD734E',
      'outerColor': '#CD734E',
      'startDate': '2025-07-14',
      'endDate': '2025-07-20',
    },
    {
      'name': 'Bastad, Sweden',
      'tour': 'ATP 250',
      'location': 'Nordea Open',
      'city': 'Bastad',
      'link': '/en/tournaments/bastad/316/overview',
      'surface': 'Clay',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-07-14',
      'endDate': '2025-07-20',
    },
    {
      'name': 'Umag, Croatia',
      'tour': 'ATP 250',
      'location': 'Plava Laguna Croatia Open Umag',
      'city': 'Umag',
      'link': '/en/tournaments/umag/439/overview',
      'surface': 'Clay',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-07-20',
      'endDate': '2025-07-26',
    },
    {
      'name': 'Washington, United States',
      'tour': 'ATP 500',
      'location': 'Mubadala Citi DC Open',
      'city': 'Washington',
      'link': '/en/tournaments/washington/418/overview',
      'surface': 'Hard',
      'innerColor': '#5A82B6',
      'outerColor': '#86A076',
      'startDate': '2025-07-21',
      'endDate': '2025-07-27',
      surfaceText: 'Washington, D.C.',
    },
    {
      'name': 'Kitzbuhel, Austria',
      'tour': 'ATP 250',
      'location': 'Generali Open',
      'city': 'Kitzbuhel',
      'link': '/en/tournaments/kitzbuhel/319/overview',
      'surface': 'Clay',
      'innerColor': '#CD734E',
      'outerColor': '#CD734E',
      'startDate': '2025-07-21',
      'endDate': '2025-07-26',
    },
    {
      'name': 'Toronto, Canada',
      'tour': 'ATP 1000',
      'location': 'National Bank Open Presented by Rogers',
      'city': 'Toronto',
      'link': '/en/tournaments/toronto/421/overview',
      'surface': 'Hard',
      'innerColor': '#5A719A',
      'outerColor': '#8B9E78',
      'startDate': '2025-07-27',
      'endDate': '2025-08-07',
      surfaceText: 'Toronto',
    },
    {
      'name': 'Cincinnati, United States',
      'tour': 'ATP 1000',
      'location': 'Cincinnati Open',
      'city': 'Cincinnati',
      'link': '/en/tournaments/cincinnati/422/overview',
      'surface': 'Hard',
      'innerColor': '#6E90CF',
      'outerColor': '#81A78B',
      'startDate': '2025-08-07',
      'endDate': '2025-08-18',
    },
    {
      'name': 'Winston-Salem, United States',
      'tour': 'ATP 250',
      'location': 'Winston-Salem Open',
      'city': 'Winston-Salem',
      'link': '/en/tournaments/winston-salem/6242/overview',
      'surface': 'Hard',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-08-17',
      'endDate': '2025-08-23',
    },
    {
      'name': 'US Open',
      'tour': 'Grand Slam',
      'location': 'US Open',
      'city': 'New York',
      'link': '/en/tournaments/us-open/560/overview',
      'surface': 'Hard',
      'innerColor': '#3c1053',
      'outerColor': '#c8a2c8',
      'startDate': '2025-08-24',
      'endDate': '2025-09-07',
    },
    {
      'name': 'Davis Cup Qualifiers 2nd Rd',
      'tour': 'ITF',
      'location': 'Davis Cup Qualifiers 2nd Rd',
      'city': 'Multiple Locations',
      'link': '/en/tournaments/davis-cup-qualifiers-2nd-rd/8097/overview',
      'surface': 'Hard',
      'innerColor': '#b71c1c',
      'outerColor': '#ffcdd2',
      'startDate': '2025-09-12',
      'endDate': '2025-09-14',
    },
    {
      'name': 'Chengdu, China',
      'tour': 'ATP 250',
      'location': 'Chengdu Open',
      'city': 'Chengdu',
      'link': '/en/tournaments/chengdu/7581/overview',
      'surface': 'Hard',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-09-17',
      'endDate': '2025-09-23',
    },
    {
      'name': 'Hangzhou, China',
      'tour': 'ATP 250',
      'location': 'Hangzhou Open',
      'city': 'Hangzhou',
      'link': '/en/tournaments/hangzhou/4713/overview',
      'surface': 'Hard',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-09-17',
      'endDate': '2025-09-23',
    },
    {
      'name': 'Laver Cup',
      'tour': 'Laver Cup',
      'location': 'Laver Cup',
      'city': 'San Francisco',
      'link': '/en/tournaments/laver-cup/9210/overview',
      'surface': 'Hard',
      'innerColor': '#d32f2f',
      'outerColor': '#1976d2',
      'startDate': '2025-09-19',
      'endDate': '2025-09-21',
    },
    {
      'name': 'Tokyo, Japan',
      'tour': 'ATP 500',
      'location': 'Kinoshita Group Japan Open Tennis Championships',
      'city': 'Tokyo',
      'link': '/en/tournaments/tokyo/329/overview',
      'surface': 'Hard',
      'innerColor': '#2e7d32',
      'outerColor': '#c8e6c9',
      'startDate': '2025-09-24',
      'endDate': '2025-09-30',
    },
    {
      'name': 'Beijing, China',
      'tour': 'ATP 500',
      'location': 'China Open',
      'city': 'Beijing',
      'link': '/en/tournaments/beijing/747/overview',
      'surface': 'Hard',
      'innerColor': '#2e7d32',
      'outerColor': '#c8e6c9',
      'startDate': '2025-09-25',
      'endDate': '2025-10-01',
    },
    {
      'name': 'Shanghai, China',
      'tour': 'ATP 1000',
      'location': 'Rolex Shanghai Masters',
      'city': 'Shanghai',
      'link': '/en/tournaments/shanghai/5014/overview',
      'surface': 'Hard',
      'innerColor': '#1565c0',
      'outerColor': '#bbdefb',
      'startDate': '2025-10-01',
      'endDate': '2025-10-12',
    },
    {
      'name': 'Almaty, Kazakhstan',
      'tour': 'ATP 250',
      'location': 'Almaty Open',
      'city': 'Almaty',
      'link': '/en/tournaments/almaty/9410/overview',
      'surface': 'Hard',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-10-13',
      'endDate': '2025-10-19',
    },
    {
      'name': 'Stockholm, Sweden',
      'tour': 'ATP 250',
      'location': 'BNP Paribas Nordic Open',
      'city': 'Stockholm',
      'link': '/en/tournaments/stockholm/429/overview',
      'surface': 'Hard',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-10-13',
      'endDate': '2025-10-19',
    },
    {
      'name': 'Brussels, Belgium',
      'tour': 'ATP 250',
      'location': 'European Open',
      'city': 'Brussels',
      'link': '/en/tournaments/brussels/7485/overview',
      'surface': 'Hard',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-10-13',
      'endDate': '2025-10-19',
    },
    {
      'name': 'Vienna, Austria',
      'tour': 'ATP 500',
      'location': 'Erste Bank Open',
      'city': 'Vienna',
      'link': '/en/tournaments/vienna/337/overview',
      'surface': 'Hard',
      'innerColor': '#2e7d32',
      'outerColor': '#c8e6c9',
      'startDate': '2025-10-20',
      'endDate': '2025-10-26',
    },
    {
      'name': 'Basel, Switzerland',
      'tour': 'ATP 500',
      'location': 'Swiss Indoors Basel',
      'city': 'Basel',
      'link': '/en/tournaments/basel/328/overview',
      'surface': 'Hard',
      'innerColor': '#2e7d32',
      'outerColor': '#c8e6c9',
      'startDate': '2025-10-20',
      'endDate': '2025-10-26',
    },
    {
      'name': 'Paris, France',
      'tour': 'ATP 1000',
      'location': 'Rolex Paris Masters',
      'city': 'Paris',
      'link': '/en/tournaments/paris/352/overview',
      'surface': 'Hard',
      'innerColor': '#1565c0',
      'outerColor': '#bbdefb',
      'startDate': '2025-10-27',
      'endDate': '2025-11-02',
    },
    {
      'name': 'Belgrade, Serbia',
      'tour': 'ATP 250',
      'location': 'Belgrade Open',
      'city': 'Belgrade',
      'link': '/en/tournaments/belgrade/4787/overview',
      'surface': 'Hard',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-11-02',
      'endDate': '2025-11-08',
    },
    {
      'name': 'Metz, France',
      'tour': 'ATP 250',
      'location': 'Moselle Open',
      'city': 'Metz',
      'link': '/en/tournaments/metz/341/overview',
      'surface': 'Hard',
      'innerColor': '#e65100',
      'outerColor': '#ffcc80',
      'startDate': '2025-11-02',
      'endDate': '2025-11-08',
    },
    {
      'name': 'Nitto ATP Finals',
      'tour': 'ATP Finals',
      'location': 'Nitto ATP Finals',
      'city': 'Turin',
      'link': '/en/tournaments/nitto-atp-finals/605/overview',
      'surface': 'Hard',
      'innerColor': '#0d47a1',
      'outerColor': '#e0e0e0',
      'startDate': '2025-11-09',
      'endDate': '2025-11-16',
    },
    {
      'name': 'Davis Cup Finals',
      'tour': 'ITF',
      'location': 'Davis Cup Finals',
      'city': 'Bologna',
      'link': '/en/tournaments/davis-cup-finals/8099/overview',
      'surface': 'Hard',
      'innerColor': '#b71c1c',
      'outerColor': '#ffcdd2',
      'startDate': '2025-11-18',
      'endDate': '2025-11-23',
    },
    {
      'name': 'Next Gen ATP Finals presented by PIF',
      'tour': 'Next Gen ATP Finals',
      'location': 'Next Gen ATP Finals presented by PIF',
      'city': 'Jeddah',
      'link': '/en/tournaments/next-gen-atp-finals/7696/overview',
      'surface': 'Hard',
      'innerColor': '#00695c',
      'outerColor': '#b2dfdb',
      'startDate': '2025-12-17',
      'endDate': '2025-12-21',
    },
  ];


// --- Tournament Data ---
// const tournaments: Tournament[] = [
//   { name: 'Australian Open', tour: 'Grand Slam', innerColor: '#3E8ACC', outerColor: '#2A7ABF' },
//   { name: 'BNP Paribas Open', tour: 'ATP & WTA 1000', innerColor: '#5D3FD3', outerColor: '#3E8ACC' },
//   { name: 'Miami Open', tour: 'ATP & WTA 1000', innerColor: '#008080', outerColor: '#005f5f' },
//   { name: 'Rolex Monte-Carlo', tour: 'ATP Masters 1000', innerColor: '#B95E42', outerColor: '#A4503A' },
//   { name: 'Mutua Madrid Open', tour: 'ATP & WTA 1000', innerColor: '#E34234', outerColor: '#C43022' },
//   { name: 'Roland-Garros', tour: 'Grand Slam', innerColor: '#D46A4A', outerColor: '#BF5B3F' },
//   { name: 'Wimbledon', tour: 'Grand Slam', innerColor: '#3A7D2A', outerColor: '#336F26' },
//   { name: 'National Bank Open', tour: 'ATP & WTA 1000', innerColor: '#2A52BE', outerColor: '#22439E' },
//   { name: 'US Open', tour: 'Grand Slam', innerColor: '#0062A8', outerColor: '#008080' },
//   { name: 'Nitto ATP Finals', tour: 'ATP Finals', innerColor: '#2E3B4E', outerColor: '#202936' },
// ];

// const tournaments: Tournament[] = [
//   // Spring Clay Season
//   { name: 'Rolex Monte-Carlo', tour: 'ATP Masters 1000', innerColor: '#B95E42', outerColor: '#A4503A' },
//   { name: 'Mutua Madrid Open', tour: 'ATP & WTA 1000', innerColor: '#E34234', outerColor: '#C43022' },
//   { name: 'Roland-Garros', tour: 'Grand Slam', innerColor: '#D46A4A', outerColor: '#BF5B3F' },
//   { name: 'Internazionali BNL d’Italia (Rome)', tour: 'ATP & WTA 1000', innerColor: '#C1440E', outerColor: '#9C3B0E' },
//   { name: 'Barcelona Open', tour: 'ATP 500', innerColor: '#CD5C5C', outerColor: '#B34747' },
//
//   // Summer Grass & Clay Season
//   { name: 'Wimbledon', tour: 'Grand Slam', innerColor: '#3A7D2A', outerColor: '#336F26' },
//   { name: 'Hamburg European Open', tour: 'ATP 500', innerColor: '#C45A3A', outerColor: '#A94A2F' },
//   { name: 'Queen’s Club Championships', tour: 'ATP 500', innerColor: '#2E8B57', outerColor: '#246B45' },
//   { name: 'Eastbourne International', tour: 'ATP & WTA 250', innerColor: '#3CB371', outerColor: '#2E8B57' },
//   { name: 'Bad Homburg Open', tour: 'WTA 250', innerColor: '#228B22', outerColor: '#1E7B1E' },
//
//   // Summer Hard Court Season
//   { name: 'National Bank Open', tour: 'ATP & WTA 1000', innerColor: '#2A52BE', outerColor: '#22439E' },
//   { name: 'Cincinnati Open', tour: 'ATP & WTA 1000', innerColor: '#7B429B', outerColor: '#3675B3' },
//   { name: 'US Open', tour: 'Grand Slam', innerColor: '#0062A8', outerColor: '#008080' },
//   { name: 'Atlanta Open', tour: 'ATP 250', innerColor: '#1E90FF', outerColor: '#1C7CD6' },
//   { name: 'Winston-Salem Open', tour: 'ATP 250', innerColor: '#4169E1', outerColor: '#3558BA' },
//
//   // Fall Indoor & Asian Hard Court Season
//   { name: 'China Open (Beijing)', tour: 'ATP & WTA 500', innerColor: '#4682B4', outerColor: '#2E5E86' },
//   { name: 'Shanghai Masters', tour: 'ATP Masters 1000', innerColor: '#5B92E5', outerColor: '#426BA9' },
//   { name: 'Paris Masters', tour: 'ATP Masters 1000', innerColor: '#3B3B98', outerColor: '#2F2F73' },
//   { name: 'Zhuhai Championships', tour: 'ATP 250', innerColor: '#3E6FB0', outerColor: '#30598F' },
//   { name: 'Tokyo Open (Rakuten Japan)', tour: 'ATP 500', innerColor: '#4169E1', outerColor: '#2C4B9B' },
//
//   // Other Major Tournaments
//   { name: 'Australian Open', tour: 'Grand Slam', innerColor: '#3E8ACC', outerColor: '#2A7ABF' },
//   { name: 'BNP Paribas Open', tour: 'ATP & WTA 1000', innerColor: '#5D3FD3', outerColor: '#3E8ACC' },
//   { name: 'Miami Open', tour: 'ATP & WTA 1000', innerColor: '#008080', outerColor: '#005f5f' },
//   { name: 'Nitto ATP Finals', tour: 'ATP Finals', innerColor: '#2E3B4E', outerColor: '#202936' },
//   { name: 'Laver Cup', tour: 'Team Event', innerColor: '#0C0C0C', outerColor: '#1C1C1C' },
// ];

// const tournaments: Tournament[] = [
//   // Spring Clay Season
//   {
//     name: 'Rolex Monte‑Carlo Masters',
//     tour: 'ATP Masters 1000',
//     innerColor: '#B95E42',
//     outerColor: '#A4503A',
//     startDate: '2025-04-06',
//     endDate: '2025-04-13',
//   },
//   {
//     name: 'Mutua Madrid Open',
//     tour: 'ATP & WTA 1000',
//     innerColor: '#E34234',
//     outerColor: '#C43022',
//     startDate: '2025-04-21',  // official sources vary: confirmed April 21–May 4 :contentReference[oaicite:1]{index=1}
//     endDate: '2025-05-04',
//   },
//   {
//     name: 'Roland‑Garros (French Open)',
//     tour: 'Grand Slam',
//     innerColor: '#D46A4A',
//     outerColor: '#BF5B3F',
//     startDate: '2025-05-25',
//     endDate: '2025-06-08',
//   },
//
//   // Summer Grass Season
//   {
//     name: 'Queen’s Club Championships',
//     tour: 'ATP 500',
//     innerColor: '#2E8B57',
//     outerColor: '#246B45',
//     startDate: '2025-06-16',
//     endDate: '2025-06-22',  // per ATP grass calendar :contentReference[oaicite:2]{index=2}
//   },
//   {
//     name: 'Eastbourne International',
//     tour: 'ATP & WTA 250 / 500',
//     innerColor: '#3CB371',
//     outerColor: '#2E8B57',
//     startDate: '2025-06-22',
//     endDate: '2025-06-28',  // combined week per grass schedule list :contentReference[oaicite:3]{index=3}
//   },
//   {
//     name: 'Wimbledon',
//     tour: 'Grand Slam',
//     innerColor: '#3A7D2A',
//     outerColor: '#336F26',
//     startDate: '2025-06-30',
//     endDate: '2025-07-13',  // confirmed via Reuters and The Sun :contentReference[oaicite:4]{index=4}
//   },
//
//   // Summer Hard Court Season
//   {
//     name: 'National Bank Open (Toronto/Montreal)',
//     tour: 'ATP & WTA 1000',
//     innerColor: '#2A52BE',
//     outerColor: '#22439E',
//     startDate: '2025-07-27',
//     endDate: '2025-08-03',  // week 31/32 per calendar :contentReference[oaicite:5]{index=5}
//   },
//   {
//     name: 'Cincinnati Open',
//     tour: 'ATP & WTA 1000',
//     innerColor: '#7B429B',
//     outerColor: '#3675B3',
//     startDate: '2025-08-07',
//     endDate: '2025-08-17',  // includes final week starting Aug 11, ends Aug 17–24 per calendar :contentReference[oaicite:6]{index=6}
//   },
//   {
//     name: 'US Open',
//     tour: 'Grand Slam',
//     innerColor: '#0062A8',
//     outerColor: '#008080',
//     startDate: '2025-08-24',
//     endDate: '2025-09-07',  // US Open week from August 24 to early September :contentReference[oaicite:7]{index=7}
//   },
//
//   // Fall Hard Court / Indoor Season
//   {
//     name: 'China Open (Beijing)',
//     tour: 'ATP & WTA 500',
//     innerColor: '#4682B4',
//     outerColor: '#2E5E86',
//     startDate: '2025-09-22',
//     endDate: '2025-09-28',  // week beginning Sept 22 per ATP calendar :contentReference[oaicite:8]{index=8}
//   },
//   {
//     name: 'Japan Open (Tokyo)',
//     tour: 'ATP 500',
//     innerColor: '#4169E1',
//     outerColor: '#2C4B9B',
//     startDate: '2025-09-22',
//     endDate: '2025-09-28',  // same week as China Open :contentReference[oaicite:9]{index=9}
//   },
//   {
//     name: 'Shanghai Masters',
//     tour: 'ATP Masters 1000',
//     innerColor: '#5B92E5',
//     outerColor: '#426BA9',
//     startDate: '2025-10-01',
//     endDate: '2025-10-08',  // week of Oct 1–7 per calendar :contentReference[oaicite:10]{index=10}
//   },
//   {
//     name: 'Paris Masters',
//     tour: 'ATP Masters 1000',
//     innerColor: '#3B3B98',
//     outerColor: '#2F2F73',
//     startDate: '2025-10-27',
//     endDate: '2025-11-02',  // calendar for week 44/45 :contentReference[oaicite:11]{index=11}
//   },
//
//   // Other Premier Events
//   {
//     name: 'Australian Open',
//     tour: 'Grand Slam',
//     innerColor: '#3E8ACC',
//     outerColor: '#2A7ABF',
//     startDate: '2025-01-12',
//     endDate: '2025-01-26',  // first Grand Slam of year as per ATP calendar :contentReference[oaicite:12]{index=12}
//   },
//   {
//     name: 'BNP Paribas Open (Indian Wells)',
//     tour: 'ATP & WTA 1000',
//     innerColor: '#5D3FD3',
//     outerColor: '#3E8ACC',
//     startDate: '2025-03-04',
//     endDate: '2025-03-17',  // early March per ATP pdf :contentReference[oaicite:13]{index=13}
//   },
//   {
//     name: 'Miami Open',
//     tour: 'ATP & WTA 1000',
//     innerColor: '#008080',
//     outerColor: '#005f5f',
//     startDate: '2025-03-18',
//     endDate: '2025-03-31',  // following Indian Wells :contentReference[oaicite:14]{index=14}
//   },
//   {
//     name: 'Nitto ATP Finals',
//     tour: 'ATP Finals',
//     innerColor: '#2E3B4E',
//     outerColor: '#202936',
//     startDate: '2025-11-09',
//     endDate: '2025-11-16',  // ATP Finals week per calendar :contentReference[oaicite:15]{index=15}
//   },
//   {
//     name: 'Laver Cup',
//     tour: 'Team Event',
//     innerColor: '#0C0C0C',
//     outerColor: '#1C1C1C',
//     startDate: '2025-09-15',
//     endDate: '2025-09-20',  // Laver Cup week per ATP calendar :contentReference[oaicite:16]{index=16}
//   },
// ];


// export const tournaments: Tournament[] = [
//   // Team Events
//   {
//     name: 'United Cup',
//     tour: 'Team Event',
//     innerColor: '#FFD700',
//     outerColor: '#FFCA00',
//     startDate: '2024-12-27',
//     endDate: '2025-01-05',
//   },
//
//   // Australian swing & early hard
//   {
//     name: 'Brisbane International',
//     tour: 'ATP 250',
//     innerColor: '#89CFF0',
//     outerColor: '#70A1B3',
//     startDate: '2024-12-29',
//     endDate: '2025-01-05',
//   },
//   {
//     name: 'Hong Kong Tennis Open',
//     tour: 'ATP 250',
//     innerColor: '#4682B4',
//     outerColor: '#315f86',
//     startDate: '2024-12-30',
//     endDate: '2025-01-05',
//   },
//   {
//     name: 'Adelaide International',
//     tour: 'ATP 250',
//     innerColor: '#1E90FF',
//     outerColor: '#1C7CD6',
//     startDate: '2025-01-06',
//     endDate: '2025-01-11',
//   },
//   {
//     name: 'ASB Classic (Auckland)',
//     tour: 'ATP 250',
//     innerColor: '#1E90FF',
//     outerColor: '#1874CD',
//     startDate: '2025-01-06',
//     endDate: '2025-01-11',
//   },
//   {
//     name: 'Australian Open',
//     tour: 'Grand Slam',
//     innerColor: '#3E8ACC',
//     outerColor: '#2A7ABF',
//     startDate: '2025-01-12',
//     endDate: '2025-01-26',
//   },
//
//   // February hard indoor / South American clay
//   {
//     name: 'Open Occitanie (Montpellier)',
//     tour: 'ATP 250',
//     innerColor: '#708090',
//     outerColor: '#546A7B',
//     startDate: '2025-01-27',
//     endDate: '2025-02-02',
//   },
//   {
//     name: 'Dallas Open',
//     tour: 'ATP 500',
//     innerColor: '#00008B',
//     outerColor: '#00006B',
//     startDate: '2025-02-03',
//     endDate: '2025-02-09',
//   },
//   {
//     name: 'Rotterdam Open',
//     tour: 'ATP 500',
//     innerColor: '#000080',
//     outerColor: '#000060',
//     startDate: '2025-02-03',
//     endDate: '2025-02-09',
//   },
//   {
//     name: 'Open 13 Provence (Marseille)',
//     tour: 'ATP 250',
//     innerColor: '#4169E1',
//     outerColor: '#3058B3',
//     startDate: '2025-02-10',
//     endDate: '2025-02-16',
//   },
//   {
//     name: 'Delray Beach Open',
//     tour: 'ATP 250',
//     innerColor: '#5F9EA0',
//     outerColor: '#4A7A81',
//     startDate: '2025-02-10',
//     endDate: '2025-02-16',
//   },
//   {
//     name: 'Argentina Open (Buenos Aires)',
//     tour: 'ATP 250',
//     innerColor: '#CD5C5C',
//     outerColor: '#B34747',
//     startDate: '2025-02-10',
//     endDate: '2025-02-16',
//   },
//   {
//     name: 'Qatar ExxonMobil Open (Doha)',
//     tour: 'ATP 500',
//     innerColor: '#008B8B',
//     outerColor: '#006F6F',
//     startDate: '2025-02-17',
//     endDate: '2025-02-22',
//   },
//   {
//     name: 'Rio Open',
//     tour: 'ATP 500',
//     innerColor: '#C1440E',
//     outerColor: '#9C3B0E',
//     startDate: '2025-02-17',
//     endDate: '2025-02-23',
//   },
//   {
//     name: 'Dubai Duty Free Championships',
//     tour: 'ATP 500',
//     innerColor: '#4682B4',
//     outerColor: '#315f86',
//     startDate: '2025-02-24',
//     endDate: '2025-03-01',
//   },
//   {
//     name: 'Acapulco (Mexican Open)',
//     tour: 'ATP 500',
//     innerColor: '#1E90FF',
//     outerColor: '#1874CD',
//     startDate: '2025-02-24',
//     endDate: '2025-03-01',
//   },
//   {
//     name: 'Chile Open (Santiago)',
//     tour: 'ATP 250',
//     innerColor: '#CD5C5C',
//     outerColor: '#B34747',
//     startDate: '2025-02-24',
//     endDate: '2025-03-02',
//   },
//
//   // Masters & US clay
//   {
//     name: 'BNP Paribas Open (Indian Wells)',
//     tour: 'ATP & WTA 1000',
//     innerColor: '#5D3FD3',
//     outerColor: '#3E8ACC',
//     startDate: '2025-03-05',
//     endDate: '2025-03-16',
//   },
//   {
//     name: 'Miami Open',
//     tour: 'ATP & WTA 1000',
//     innerColor: '#008080',
//     outerColor: '#005f5f',
//     startDate: '2025-03-19',
//     endDate: '2025-03-30',
//   },
//   {
//     name: 'Houston (U.S. Men`s Clay Court Championship)',
//     tour: 'ATP 250',
//     innerColor: '#C1440E',
//     outerColor: '#9C3B0E',
//     startDate: '2025-03-31',
//     endDate: '2025-04-06',
//   },
//
// // European clay
//   {
//     name: 'Rolex Monte‑Carlo Masters',
//     tour: 'ATP Masters 1000',
//     innerColor: '#B95E42',
//     outerColor: '#A4503A',
//     startDate: '2025-04-06',
//     endDate: '2025-04-13',
//   },
//   {
//     name: 'Barcelona Open',
//     tour: 'ATP 500',
//     innerColor: '#CD5C5C',
//     outerColor: '#B34747',
//     startDate: '2025-04-14',
//     endDate: '2025-04-20',
//   },
//   {
//     name: 'Munich (BMW Open)',
//     tour: 'ATP 500',
//     innerColor: '#CD5C5C',
//     outerColor: '#A94A2F',
//     startDate: '2025-04-14',
//     endDate: '2025-04-20',
//   },
//   {
//     name: 'Madrid Open',
//     tour: 'ATP & WTA 1000',
//     innerColor: '#E34234',
//     outerColor: '#C43022',
//     startDate: '2025-04-23',
//     endDate: '2025-05-04',
//   },
//   {
//     name: 'Internazionali BNL d’Italia (Rome)',
//     tour: 'ATP & WTA 1000',
//     innerColor: '#C1440E',
//     outerColor: '#9C3B0E',
//     startDate: '2025-05-07',
//     endDate: '2025-05-18',
//   },
//   {
//     name: 'Hamburg Open',
//     tour: 'ATP 500',
//     innerColor: '#C45A3A',
//     outerColor: '#A94A2F',
//     startDate: '2025-05-18',
//     endDate: '2025-05-24',
//   },
//   {
//     name: 'Geneva Open',
//     tour: 'ATP 250',
//     innerColor: '#CD5C5C',
//     outerColor: '#B34747',
//     startDate: '2025-05-18',
//     endDate: '2025-05-24',
//   },
//   {
//     name: 'Roland Garros',
//     tour: 'Grand Slam',
//     innerColor: '#D46A4A',
//     outerColor: '#BF5B3F',
//     startDate: '2025-05-25',
//     endDate: '2025-06-08',
//   },
//
// // Grass season
//   {
//     name: 'Stuttgart BOSS OPEN',
//     tour: 'ATP 250',
//     innerColor: '#3CB371',
//     outerColor: '#2E8B57',
//     startDate: '2025-06-09',
//     endDate: '2025-06-15',
//   },
//   {
//     name: 'Libema Open (Hertogenbosch)',
//     tour: 'ATP 250',
//     innerColor: '#3CB371',
//     outerColor: '#2E8B57',
//     startDate: '2025-06-09',
//     endDate: '2025-06-15',
//   },
//   {
//     name: 'Queen’s Club Championships (HSBC)',
//     tour: 'ATP & WTA 500',
//     innerColor: '#2E8B57',
//     outerColor: '#246B45',
//     startDate: '2025-06-16',
//     endDate: '2025-06-22',
//   },
//   {
//     name: 'Halle (Terra Wortmann Open)',
//     tour: 'ATP 500',
//     innerColor: '#2E8B57',
//     outerColor: '#246B45',
//     startDate: '2025-06-16',
//     endDate: '2025-06-22',
//   },
//   {
//     name: 'Mallorca Championships',
//     tour: 'ATP 250',
//     innerColor: '#3CB371',
//     outerColor: '#2E8B57',
//     startDate: '2025-06-22',
//     endDate: '2025-06-28',
//   },
//   {
//     name: 'Eastbourne International',
//     tour: 'ATP & WTA 250',
//     innerColor: '#3CB371',
//     outerColor: '#2E8B57',
//     startDate: '2025-06-23',
//     endDate: '2025-06-28',
//   },
//   {
//     name: 'Wimbledon',
//     tour: 'Grand Slam',
//     innerColor: '#3A7D2A',
//     outerColor: '#336F26',
//     startDate: '2025-06-30',
//     endDate: '2025-07-13',
//   },
//
// // Summer hardcourt North America
//   {
//     name: 'Los Cabos Open',
//     tour: 'ATP 250',
//     innerColor: '#1E90FF',
//     outerColor: '#1C7CD6',
//     startDate: '2025-07-14',
//     endDate: '2025-07-20',
//   },
//   {
//     name: 'Nordea Open (Båstad / Swedish Open)',
//     tour: 'ATP 250',
//     innerColor: '#CD5C5C',
//     outerColor: '#B34747',
//     startDate: '2025-07-07',
//     endDate: '2025-07-20',
//   },
//   {
//     name: 'Generali Open Kitzbühel',
//     tour: 'ATP 250',
//     innerColor: '#CD5C5C',
//     outerColor: '#A94A2F',
//     startDate: '2025-07-20',
//     endDate: '2025-07-26',
//   },
//   {
//     name: 'National Bank Open',
//     tour: 'ATP & WTA 1000',
//     innerColor: '#2A52BE',
//     outerColor: '#22439E',
//     startDate: '2025-07-27',
//     endDate: '2025-08-07',
//   },
//   {
//     name: 'Cincinnati Open',
//     tour: 'ATP & WTA 1000',
//     innerColor: '#7B429B',
//     outerColor: '#3675B3',
//     startDate: '2025-08-07',
//     endDate: '2025-08-18',
//   },
//   {
//     name: 'Winston‑Salem Open',
//     tour: 'ATP 250',
//     innerColor: '#4169E1',
//     outerColor: '#3558BA',
//     startDate: '2025-08-17',
//     endDate: '2025-08-23',
//   },
//   {
//     name: 'US Open',
//     tour: 'Grand Slam',
//     innerColor: '#0062A8',
//     outerColor: '#008080',
//     startDate: '2025-08-24',
//     endDate: '2025-09-07',
//   },
//
// // Asian swing & indoor hard
//   {
//     name: 'Chengdu Open',
//     tour: 'ATP 250',
//     innerColor: '#4682B4',
//     outerColor: '#2E5E86',
//     startDate: '2025-09-17',
//     endDate: '2025-09-23',
//   },
//   {
//     name: 'Japan Open (Tokyo)',
//     tour: 'ATP 500',
//     innerColor: '#4169E1',
//     outerColor: '#2C4B9B',
//     startDate: '2025-09-24',
//     endDate: '2025-09-28',
//   },
//   {
//     name: 'China Open (Beijing)',
//     tour: 'ATP 500',
//     innerColor: '#4682B4',
//     outerColor: '#2E5E86',
//     startDate: '2025-09-24',
//     endDate: '2025-09-28',
//   },
//   {
//     name: 'Shanghai Masters',
//     tour: 'ATP Masters 1000',
//     innerColor: '#5B92E5',
//     outerColor: '#426BA9',
//     startDate: '2025-10-01',
//     endDate: '2025-10-08',
//   },
//   {
//     name: 'Vienna (Erste Bank Open)',
//     tour: 'ATP 500',
//     innerColor: '#708090',
//     outerColor: '#546A7B',
//     startDate: '2025-10-13',
//     endDate: '2025-10-20',
//   },
//   {
//     name: 'Swiss Indoors (Basel)',
//     tour: 'ATP 500',
//     innerColor: '#708090',
//     outerColor: '#546A7B',
//     startDate: '2025-10-13',
//     endDate: '2025-10-20',
//   },
//   {
//     name: 'Almaty Open',
//     tour: 'ATP 250',
//     innerColor: '#708090',
//     outerColor: '#546A7B',
//     startDate: '2025-10-20',
//     endDate: '2025-10-26',
//   },
//   {
//     name: 'Paris Masters',
//     tour: 'ATP Masters 1000',
//     innerColor: '#3B3B98',
//     outerColor: '#2F2F73',
//     startDate: '2025-10-27',
//     endDate: '2025-11-02',
//   },
//   {
//     name: 'Belgrade Open',
//     tour: 'ATP 250',
//     innerColor: '#708090',
//     outerColor: '#546A7B',
//     startDate: '2025-11-02',
//     endDate: '2025-11-08',
//   },
//   {
//     name: 'Moselle Open (Metz)',
//     tour: 'ATP 250',
//     innerColor: '#708090',
//     outerColor: '#546A7B',
//     startDate: '2025-11-02',
//     endDate: '2025-11-08',
//   },
//
// // Season finales
//   {
//     name: 'Nitto ATP Finals',
//     tour: 'ATP Finals',
//     innerColor: '#2E3B4E',
//     outerColor: '#202936',
//     startDate: '2025-11-09',
//     endDate: '2025-11-16',
//   },
//
//   {
//     name: 'Laver Cup',
//     tour: 'Team Event',
//     innerColor: '#0C0C0C',
//     outerColor: '#1C1C1C',
//     startDate: '2025-09-23',
//     endDate: '2025-09-28',
//   },
// ];
